version: "3"

services:
    web_front:
        container_name: gatsby_web_front
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./my-site/:/my-site
        tty: true
        ports:
            - 8000:8000
            - 9929:9929
        # entrypoint: /code/entrypoint.sh
